#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /index.php/home
        permanent: true